{\reset@font\mtcSfont\mtc@string\contentsline{section}{\noexpand \leavevmode \numberline {2.1}Apresentação da Entidade de Acolhimento}{\reset@font\mtcSfont 4}{section.2.1}}
{\reset@font\mtcSfont\mtc@string\contentsline{section}{\noexpand \leavevmode \numberline {2.2}Equipa onde se insere o estagiário}{\reset@font\mtcSfont 4}{section.2.2}}
{\reset@font\mtcSfont\mtc@string\contentsline{section}{\noexpand \leavevmode \numberline {2.3}Enquadramento Pessoal na Equipa}{\reset@font\mtcSfont 4}{section.2.3}}
