{\reset@font\mtcSfont\mtc@string\contentsline{section}{\noexpand \leavevmode \numberline {4.1}Atividades desenvolvidas}{\reset@font\mtcSfont 10}{section.4.1}}
{\reset@font\mtcSSfont\mtc@string\contentsline{subsection}{\noexpand \leavevmode \numberline {4.1.1}Modelação da Base de Dados e Backend}{\reset@font\mtcSSfont 10}{subsection.4.1.1}}
{\reset@font\mtcSSfont\mtc@string\contentsline{subsection}{\noexpand \leavevmode \numberline {4.1.2}Desenvolvimento Frontend / Aplicação Móvel}{\reset@font\mtcSSfont 10}{subsection.4.1.2}}
{\reset@font\mtcSSfont\mtc@string\contentsline{subsection}{\noexpand \leavevmode \numberline {4.1.3}Integração de Funcionalidades Principais}{\reset@font\mtcSSfont 10}{subsection.4.1.3}}
{\reset@font\mtcSfont\mtc@string\contentsline{section}{\noexpand \leavevmode \numberline {4.2}Resultados obtidos}{\reset@font\mtcSfont 10}{section.4.2}}
